LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := VollaNlp
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := shared
LOCAL_SRC_FILES := VollaNlp.apk
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := VollaGSMNlp
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := shared
LOCAL_SRC_FILES := VollaGSMNlp.apk
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)
